dist: xenial

language: c



compiler:
  - clang
  - gcc

before_script:
  - scripts/install_bsp.sh

script:
  # First, we make and test the /primes code.
  - cmake primes && make
  - primes/bin/test_sieve && primes/bin/test_utils

  # TODO: The final project
