dist:
  bionic

language:
  c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - clang-format

before_install:
  - scripts/upgrade_cmake.sh
  - scripts/install_bsp.sh
  - scripts/install_unity.sh

script:
  # Make and test the /primes code.
  - cmake primes -DCMAKE_BUILD_TYPE=DEBUG
  - make

  - bin/test_sieve
  - bin/test_utils

  # Clean-up previous build files before next assignment runs.
  - git clean -f

  # Make and test the /ccl code.
  - cmake ccl -DCMAKE_BUILD_TYPE=DEBUG
  - make

  - bin/test_algorithm
  - bin/test_component
  - bin/test_io
  - bin/test_segment

  # Format check for all code under /ccl.
  - scripts/format.sh
