dist: xenial

language: c

addons:
  apt:
    packages:
      - cmake

compiler:
  - gcc

before_script:
  - scripts/install_bsp.sh
  - scripts/install_unity.sh

script:
  # First, we make and test the /primes code.
  - cmake primes && make
  - primes/bin/test_sieve && primes/bin/test_utils

  # TODO: The final project
