dist:
  bionic

language:
  c

compiler:
  - gcc
  - clang

before_install:
  - scripts/upgrade_cmake.sh
  - scripts/install_bsp.sh
  - scripts/install_oclint.sh
  - scripts/install_unity.sh

script:
  # First, we make and test the /primes code.
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON primes
  - make

  - bin/test_sieve
  - bin/test_utils

  # See e.g. https://github.com/oclint/oclint/issues/200
  - "${TRAVIS_BUILD_DIR}"/oclint/bin/oclint-json-compilation-database

  # TODO: The final project
