dist:
  bionic

language:
  c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - clang-format

before_install:
  - scripts/upgrade_cmake.sh
  - scripts/install_bsp.sh
  - scripts/install_unity.sh

script:
  # Make and test the /primes code.
  - cmake -DCMAKE_BUILD_TYPE=DEBUG primes
  - make

  - bin/test_sieve
  - bin/test_utils

  # Make and test the /cat code.
  - cmake -DCMAKE_BUILD_TYPE=DEBUG cat
  - make

  # TODO tests

  # Format check for all code under /cat.
  - scripts/format.sh
